name: Sync canvas to Gist
on:
  push:
    paths:
      - 'otomatik-kanvas-denemesi.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read canvas and update Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Reading canvas file..."
          FILE="otomatik-kanvas-denemesi.md"
          CONTENT=$(cat "$FILE")
          echo "Patching Gist..."
          curl -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"files\": {\"$FILE\": {\"content\": \"$CONTENT\"}}}" \
            https://api.github.com/gists/5d10b9b6f84ea174da9a86968fbc7caf
